mappings:
  ExternalURL: Sunnysideup\ExternalURLField\ExternalURL
  ExternalURLField: Sunnysideup\ExternalURLField\ExternalURLField
  ExternalURLFieldTest: Sunnysideup\ExternalURLField\Tests\ExternalURLFieldTest
  ExternalURLTest: Sunnysideup\ExternalURLField\Tests\ExternalURLTest
